#!/bin/sh

# Make sure script is not executed
exit 0

git config --local user.name "John Doe"
git config --local user.email "12345+johndoe@users.noreply.github.com"
git config --local user.signingkey "1A2B3C4D5E"
#git config --local commit.gpgsign false

