#!/usr/bin/env bash

PREFIX_PATH="$(git rev-parse --show-toplevel)/.git-commit-prefix"

abort() {
  echo $1
	exit 1
}

branch=$(git current-head)
[[ ! -f $PREFIX_PATH ]] && ([[ $branch != "feature/"* ]] || [[ $branch != "hotfix/"* ]] || [[ $branch != "sprint-"* ]]) && abort "Not on a feature/hotfix branch"

feature=""
style="0"

if [[ -f $PREFIX_PATH ]] ; then
	style="1"
	feature=$(cat $PREFIX_PATH)
elif [[ $branch != "sprint-"* ]] ; then
	style="1"
	feature=$(echo -n $branch | sed "s/[^\/]*\///")
else
	style="2"
	feature=$(echo -n $branch | awk -F '[-_]' '{print $3}')
fi

if [[ $style == "1" ]] ; then
	git commit -am "$feature $*"
elif [[ $style == "2" ]] ; then
	git commit -am "#$feature: $*"
fi

