#!/usr/bin/env bash

branch=$(git current-head)
([[ $branch != "feature/"* ]] || \
	[[ $branch != "hotfix/"* ]] || \
	[[ $branch != "sprint-"* ]]) \
	|| (echo "Not on a feature/hotfix branch" && exit 1)

feature=""
style="0"

if [[ $branch != "sprint-"* ]] ; then
	style="1"
	feature=$(echo -n $branch | sed "s/[^\/]*\///")
else
	style="2"
	feature=$(echo -n $branch | awk -F "-" '{print $3}')
fi

if [[ $style == "1" ]] ; then
	git commit -am "$feature $*"
elif [[ $style == "2" ]] ; then
	git commit -am "#$feature: $*"
fi

