[colors.normal]
black = "#000000"
blue = "#5394ec"
cyan = "#299999"
green = "#379c1a"
magenta = "#ae8abe"
red = "#e74644"
white = "#eeeeee"
yellow = "#dcc457"

[colors.primary]
background = "#000000"
foreground = "#a9b7c6"

[cursor]
blink_interval = 500

[cursor.style]
blinking = "Always"

[font]
size = 11

[font.bold]
family = "JetBrains Mono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrains Mono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrains Mono Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Numpad0"
mods = "Control"

[[keyboard.bindings]]
action = "Paste"
key = "Insert"
mods = "Shift"

[[mouse.bindings]]
action = "None"
mouse = "Middle"

[schemes.darcula.normal]
black = "#000000"
blue = "#5394ec"
cyan = "#299999"
green = "#379c1a"
magenta = "#ae8abe"
red = "#e74644"
white = "#eeeeee"
yellow = "#dcc457"

[schemes.darcula.primary]
background = "#000000"
foreground = "#a9b7c6"

[selection]
save_to_clipboard = true

[window]
opacity = 0.7
