#!/bin/sh

case $1 in
	on) xrandr --output DisplayPort-1 --auto --scale 2x2 --right-of DisplayPort-0 ;;
	off) xrandr --output DisplayPort-1 --off ;;
	*) echo "Usage: screen [on|off]" ; exit 1 ;;
esac

